version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-proposia
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: proposals_db
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 1
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

  redis:
    image: redis:latest
    container_name: redis-proposia
    restart: always
    ports:
      - "6379:6379"
