name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      QUAY_REPO: ${{ secrets.QUAY_REPO }}
      TAG: latest
      PLATFORM: linux/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.QUAY_REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          platforms: ${{ env.PLATFORM }}
